#!/bin/ash
# RFHS checker script for realtime troubleshooting, status checking, and CI/CD
# check for ssid's and services working

set -eu

status_dir='/root/shared_persistent_storage'
[ ! -d "${status_dir}" ] && mkdir -p "${status_dir}"
# Write to a tmpdir and move it into place after finishing creating the file content
apstatus="$(mktemp)"
apstatusfinal="${status_dir}/AP_status"

printf "# This file is auto generated once per minute (ideally) and NEVER read by anything\n" | tee "${apstatus}"
printf '# Last generation start time %s (compare to "date" command)\n' "$(date)" | tee -a "${apstatus}"

fail_count=0
service_fail_count=0
if [ "${1:-}" = "excessive" ]; then
  excessive=1
else
  excessive=0
fi
if [ "${1:-}" = "bootwifi" ]; then
  bootwifi=1
else
  bootwifi=0
fi

wait_for_it() {
  iter=0
  if [ "${excessive}" = "1" ]; then
    while pgrep -f rfhs_wifi_fixer > /dev/null; do
      if [ "${iter}" -ge "60" ]; then
        printf "Timeout waiting for rfhs_wifi_fixer to do it's job.\n" | tee -a "${apstatus}"
        mv "${apstatus}" "${apstatusfinal}"
        exit 1
      fi
      printf "rfhs_wifi_fixer is prepping the system...\n" | tee -a "${apstatus}"
      sleep 1
      iter=$((iter + 1))
    done
  fi
  while pgrep -f mac80211.sh > /dev/null; do
    if [ "${iter}" -ge "60" ]; then
      printf "Timeout waiting for mac80211.sh to do it's job.\n" | tee -a "${apstatus}"
      mv "${apstatus}" "${apstatusfinal}"
      exit 1
    fi
    printf "mac802.11.sh is configuring interfaces...\n" | tee -a "${apstatus}"
    sleep 1
    iter=$((iter + 1))
  done
  while pgrep -f 'ubus call hostapd' > /dev/null 2>&1; do
    if [ "${iter}" -ge "60" ]; then
      printf "Timeout waiting for 'ubus call hostapd to do it's job.\n" | tee -a "${apstatus}"
      mv "${apstatus}" "${apstatusfinal}"
      exit 1
    fi
    printf "ubus is still configuring hostapd...\n" | tee -a "${apstatus}"
    sleep 1
    iter=$((iter + 1))
  done
  return 0
}

do_check() {
  check=0
  config="$(mktemp)"
  running="$(mktemp)"

  # Write status files which may or may not be used by code you will never see...
  if [ -d '/run/rfctf_status' ]; then
    for ssid in $(iwinfo | grep 'ESSID:' | awk '{gsub(/"/, "");print $3}' | sort -u | grep -v unknown); do
      touch "/run/rfctf_status/${ssid}_ap_running"
    done
  fi

  # get info for config check
  grep ' ssid ' /etc/config/wireless | grep -v '^#' | awk '{gsub("\047","");print $3}' | sort > "${config}"
  iwinfo | grep 'ESSID:' | awk '{gsub(/"/, "");print $3}' | sort | grep -v unknown > "${running}"
  # config check
  if ! diff -Naur "${config}" "${running}" > /dev/null 2>&1; then
    OLDIFS="${IFS}"
    IFS='
'
    for line in $(diff -Naur "${config}" "${running}"); do
      if echo "${line}" | grep -q -- '---'; then
        continue
      elif echo "${line}" | grep -q -- '+++'; then
        continue
      elif echo "${line}" | grep -q -- '@@'; then
        continue
      elif echo "${line}" | grep -q -- 'unknown'; then
        continue
      elif printf "%s" "${line}" | grep -q 'OpenWrt'; then
        continue
      fi
      if echo "${line}" | grep -q '^+'; then
        check=1
        printf '%s is running but not configured???\n' "${line/+/}" | tee -a "${apstatus}"
        iwinfo | grep -A1 -- "${line/+/}" | tee -a "${apstatus}"
      fi
      if echo "${line}" | grep -q '^-'; then
        check=1
        printf '%s is configured but not running\n' "${line/-/}" | tee -a "${apstatus}"
        printf '\nUCI CONFIG:\n' | tee -a "${apstatus}"
        grep -v '^#' /etc/config/wireless | grep -A1 -- " ssid .${line/-/}" | tee -a "${apstatus}"
        printf '\nHOSTAPD Config:\n' | tee -a "${apstatus}"
        awk "/^ssid=${line/-/}/{print FILENAME}" /var/run/*.conf | tee -a "${apstatus}"
        printf '\nRUNNING:\n' | tee -a "${apstatus}"
        iwinfo | grep -A2 -- "${line/-/}" | tee -a "${apstatus}"
        printf "-------------------------------------------\n" | tee -a "${apstatus}"
      fi
    done
    IFS="${OLDIFS}"
  fi
  rm -f "${config}" "${running}"
  for phy in $(grep ' phy ' /etc/config/wireless | grep -v '^#' | awk '{gsub("\047","");print $3}' | sort); do
    if ! iw "${phy}" info > /dev/null 2>&1; then
      check=1
      printf '%s is configured but missing\n' "${phy}" | tee -a "${apstatus}"
    fi
  done
  if [ "${check}" = "0" ]; then
    printf 'AP Status: Running config matches written config\n' | tee -a "${apstatus}"
    printf 'Wifi is UP\n' | tee -a "${apstatus}"
  else
    if pgrep -f mac80211.sh > /dev/null 2>&1; then
      check=1
      printf '-------------------------------------------\n' | tee -a "${apstatus}"
      printf "OpenWRT is still has mac80211.sh configuration processes running.\n" | tee -a "${apstatus}"
    fi
  fi
  return "${check}"
}

check_services() {
  service_check=0
  # Checking for pop3, and dhcp, but NOT dns or https because those bind to ip not all
  for port in 110; do
    if ! ss -nlt | grep -q "0.0.0.0:${port}"; then
      printf 'Nothing is listening on tcp port %s\n' "${port}" | tee -a "${apstatus}"
      service_check=1
    fi
  done
  for port in 67; do
    if ! ss -nlu | grep -q "0.0.0.0:${port}"; then
      printf 'Nothing is listening on udp port %s\n' "${port}" | tee -a "${apstatus}"
      service_check=1
    fi
  done
  if [ "${service_fail_count}" -gt "0" ]; then
    ss -nlup | tee -a "${apstatus}"
    service_check=1
  fi
  return "${service_check}"
}

if [ -f '.dockerenv' ]; then
  boot_timestamp="$(stat -c %Y /.dockerenv)"
  target_time=$(( 30 + boot_timestamp ))
  sleepy_tyme=$(( target_time - $(date +%s) ))
else
  # not in docker, assume uptime is when we booted
  sleepy_tyme=$(( 60 - $(awk -F. '{print $1}' /proc/uptime) ))
fi
if [ "${sleepy_tyme}" -gt "0" ]; then
  if [ "${sleepy_tyme}" -gt "60" ]; then
    #if the time skews during/after boot this number can end up huge
    #limit it to the a sane maximum
    sleepy_tyme=60
    #time looks skewed, so fix it for the next run
    #this will make the loop always think it's in docker but also not sleep every time it runs
    touch .dockerenv
  fi
  printf 'Sleeping for %ss while system is booting...\n' "${sleepy_tyme}" | tee -a "${apstatus}"
  sleep "${sleepy_tyme}"
fi

if [ "${excessive}" = "1" ]; then
  for required_command in rfhs_predictable_phys grep sort iw sed xargs wc lsmod rmmod; do
    if [ ! -x "$(command -v ${required_command} 2>&1)" ]; then
      printf "Missing required command: %s\n" "${required_command}" | tee -a "${apstatus}"
      fail_count=$((fail_count + 1))
    fi
  done
  for rfhs_command in iptables cat ip fakepop ss; do
    if [ ! -x "$(command -v ${rfhs_command} 2>&1)" ]; then
      printf "Missing rfhs command: %s\n" "${rfhs_command}" | tee -a "${apstatus}"
      fail_count=$((fail_count + 1))
    fi
  done
fi
wait_for_it
sleep 1
wait_for_it
if do_check; then
  printf "Check Pass\n" | tee -a "${apstatus}"
else
  printf "Check Failed\n" | tee -a "${apstatus}"
  fail_count=$((fail_count + 1))
fi

# If we found something wrong
if [ "${fail_count}" -gt "0" ]; then
  # and we are doing a normal check
  if [ "${excessive}" = "0" ]; then
    # Kick the wifi to see if it recovers.
    printf "Failures found, restarting wifi to attempt auto recovery...\n" | tee -a "${apstatus}"
    wifi up
    printf "Wifi restart triggered, run rfhs_checker again in 60s...\n" | tee -a "${apstatus}"
  fi
fi

# Add a check for setageing?

if [ "${bootwifi}" = "0" ]; then
  if check_services; then
    printf 'Service Check Pass\n' | tee -a "${apstatus}"
  else
    printf 'Service Check Failed\n' | tee -a "${apstatus}"
    fail_count=$((fail_count + 1))
  fi
fi

printf 'Checker run completed\n' | tee -a "${apstatus}"
# Move the file into place right before exiting
mv "${apstatus}" "${apstatusfinal}"
exit "${fail_count}"
